### PR TITLE
Update unipi with MirageOS 4

### PR DESCRIPTION
**Pull request by dinosaure**
Mainly a deletion of devices and some renaming about command-line options. Feel free to update/change documentations/names of theses options (specially `tls-authenticator`).

### CODE REVIEW

**Comment by hannesm** [comment]
Thanks for your work. Since we are building binary releases of unipi at https://builds.robur.coop, and mirage 4 is not yet compatible with orb, we won't be able to merge this before ocamllabs/opam-monorepo#234 is merged, released, and used by mirage.

**Comment by dinosaure** [comment]
I added the usage of [`conan`](https://github.com/mirage/conan) and this version of `unipi` is currently used for my blog (https://blog.osau.re). It seems to work but I think the image is bigger (~ 26M due to the `conan` database).

**Comment by hannesm** [comment]
Hmm, ~26MB due to `conan` database -- I wonder how much of that code is used commonly in such a unikernel, and whether something smaller or simpler could be done? Is the entire database useful in the first place?

**Comment by dinosaure** [comment]
> in such a unikernel, and whether something smaller or simpler could be done? Is the entire database useful in the first place?

The database is already linted to introduce only MIME type (the `file`'s database is bigger because it permits a description of a file such as the size of a `*.png` for instance). We can reduce the size of the database and pick only few descriptions (like images, xml documents, etc.) because we currently handle lot of MIME types. But I don't know which set of MIME type you want to handle.

**Comment by hannesm** [comment]
Well, me neither. I'm curious whether just using the file endings would be sufficient (assuming that'd be smaller)? Or keeping the database in a block storage (though that'd make the setup more complicated).

**Comment by dinosaure** [comment]
> Or keeping the database in a block storage (though that'd make the setup more complicated).

It's another possibility which can be, indeed, interesting. Currently, we handle ~1500 MIME types. I will try to only use few of them (currently, we are able to recognize something like `application/x-epoc-jotter`...) and come back with a probably smaller unikernel.

**Comment by hannesm** [comment]
Would another potential approach be to access the mime type from git (does git provide this information? -- I know it has some of that information for treating files as binary etc.). I'm really uneasy about doubling unipi's size.

**Comment by dinosaure** [comment]
> Would another potential approach be to access the mime type from git (does git provide this information?

Unfortunately, such information does not exists with Git core 😕 

> I'm really uneasy about doubling unipi's size.

Yeah, I agree with you. It's an experimentation and 3 solutions exists for us:
1) lint the database to include only what we really need (many MIME types are just obsolete)
2) upgrade `conan` to provide from the database a binding between `:!ext` and `!:mime` (as `ocaml-magic-mime`)
3) just use `ocaml-magic-mime`

**Comment by hannesm** [comment]
Since (3) is what unipi does at the moment, what was your motivation for a change? And does `conan` figure out the right mime type of e.g. javascript or xml or html files?

**Comment by dinosaure** [comment]
> And does conan figure out the right mime type of e.g. javascript or xml or html files?

This is the main diff between `ocaml-magic-mime` and `conan`.

`ocaml-magic-mime` just look up the extension of the filename and say that if it's an `*.mp3`, it's an audio - even if it can be an executable. This is why I talk about what we should trust, the contents of the file or the filename?

`conan` is a re-implementation of `file` which looks into the given file and try to recognize (as a detective) a certain pattern described by a database. At some point and along our decision tree, we are confident that the file has a certain MIME type. For instance, for an image, `conan` will look into the file and try to see if inherent values expected for a PNG file exists and if it's the case, it tells you that what you have is a PNG image.

The `conan` database is big: it can recognize 1500 MIME types. That mostly means that you have a description of... 1500 formats (zlib, html, mp3, jpeg, png, ocaml, ELF, amiga font...). As I said, most of them are obsolete and we should not find them into a store which want to contains a static website.

So depending on what you want:
- if you want to trust only on the filename and its extension, `ocaml-magic-mime` is the best. `conan` can generate something more exhaustive in the same way but it's not the original goal of `conan`
- if you want something more robust which try to recognize the MIME type regardless the filename (and trust only contents of the given file), `conan` is your solution. Again, the current database is big because I included everything (even the description of the `amiga-font`...)

**Comment by hannesm** [comment]
Thanks for your explanation. I'm aware that `conan` infers the mime type of various binaries depending on some magic values / strings embedded at certain positions.

Now, my question is for plain text files, does `conan` always use "text/plain", or does it infer the correct mime type for html/xml/svg/js?

**Comment by dinosaure** [comment]
> Now, my question is for plain text files, does conan always use "text/plain", or does it infer the correct mime type for html/xml/svg/js?

According to the database, it is able to recognize SVG, HTML and XML. The description of JavaScript or even CSS does not really exist - however, in that case and in our context, I use the `type=""` field into the `<link ...>` database and my web browser interprets correctly such things. It recognize images if you use some too. If it did not find a solution, you must find a default behavior (say nothing about the `Content-Type` as I did or say a default MIME type like `application/octet-stream`).

**Comment by hannesm** [comment]
thanks, this has been incorporated into the main branch via #9

**Pull request closed without merging**
