### PR TITLE
Mirage4 port attempt

### PR DESCRIPTION
**Pull request by reynir**
I deleted code in config.ml, looked at @dinosaure's pasteur for help with the new mirage api for git, and then guided myself through the compiler errors by looking at the relevant irmin files.

Below is the .opam.locked file that might be helpful in figuring version constraints on the relevant packages.

[unipi-spt.opam.locked.txt](https://github.com/roburio/unipi/files/9277266/unipi-spt.opam.locked.txt)

### CODE REVIEW

**Comment by reynir** [comment]
Ah, I should have checked for existing PRs! I didn't see #7.

**Comment by hannesm** [comment]
So, would you be willing to look at #7 and compare/merge the things into this one? I'm in favour of continuing with Magic_mime for now.

About the CI setup, to get MirageOS4 there you may want to look into https://github.com/roburio/traceroute/blob/main/.cirrus.yml (and copy that over modulo the naming parts).

**Comment by reynir** [comment]
Reading the irmin changelog I see there's a new `Irmin.Contents.String_v2` because `Irmin.Contents.String` has changed hash. I'm not certain what this means for cloning git repositories... But we should maybe be using  `Irmin.Contents.String_v2` then?
https://github.com/mirage/irmin/pull/1715

**Comment by reynir** [comment]
I asked in https://github.com/mirage/irmin/issues/2053 what consequences using `Irmin.Contents.{String,String_v2}` may have when interacting with a remote git repository. The answer I got was that it **should** be fine to use the new `Irmin.Contents.String` as the hash is overridden in the backend.

Furhtermore, I decided to shorten the description for `--tls-authenticator` from including the whole description of the authenticator format to just a reference to mirage.mli. I also opened an issue with ocaml-git about reporting the expected format in the parse error message: https://github.com/mirage/ocaml-git/issues/582

**Pull request merged**
